language: haskell
install:
  - cabal install --only-dependencies --enable-tests
  - cabal configure --enable-tests
  - cabal build
script:
  - cabal test --show-details=always
notifications:
  email: false